import React from 'react';
import PageTransition from '../components/PageTransition';
import ScrollReveal from '../components/ScrollReveal';

export default function PrivacyPolicy() {
  return (
    <PageTransition>
      <div className="mx-auto max-w-4xl px-6 py-12">
        <ScrollReveal direction="up">
          <h1 className="font-display text-4xl font-semibold text-slate-900">Privacy Policy</h1>
          <p className="mt-4 text-slate-500">Effective Date: {new Date().toLocaleDateString()}</p>

          <div className="mt-8 space-y-8 text-slate-600">
            <section>
              <h2 className="text-2xl font-semibold text-slate-800">1. Introduction</h2>
              <p className="mt-3">
                Welcome to Corelign ("we", "our", or "us"). We are committed to protecting your privacy and ensuring you have a positive experience on our platform. This Privacy Policy explains how we collect, use, and safeguard your information, particularly regarding our AI-driven document intelligence services.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-slate-800">2. Zero Training Guarantee</h2>
              <p className="mt-3">
                <strong>Your data remains yours.</strong> We explicitly guarantee that any documents you upload, queries you make, and responses generated by our system are <strong>never</strong> used to train, improve, or fine-tune any public or foundational AI models (including those provided by third parties). Your data is processed solely to provide you with search and retrieval services within your private workspace.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-slate-800">3. Information We Collect</h2>
              <ul className="mt-3 list-disc pl-5 space-y-2">
                <li><strong>Account Information:</strong> Name, email address, and authentication credentials when you register.</li>
                <li><strong>User Content:</strong> Documents (e.g., PDFs, DOCX) you upload to the platform for indexing and retrieval.</li>
                <li><strong>Usage Data:</strong> System logs, query history, and analytics to ensure platform performance and security.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-slate-800">4. How We Process Your Data (Vectorization)</h2>
              <p className="mt-3">
                To provide our intelligent search features, uploaded documents are securely processed and converted into mathematical representations (vector embeddings). These embeddings cannot be reverse-engineered into the original text by unauthorized parties and are stored securely within our infrastructure to facilitate rapid, context-aware retrieval.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-slate-800">5. Data Security & Storage</h2>
              <p className="mt-3">
                We implement industry-standard security measures, including encryption in transit (TLS) and at rest (AES-256), to protect your personal information and documents against unauthorized access, alteration, or destruction. We utilize secure third-party sub-processors for cloud hosting and LLM API services, all of which are bound by strict confidentiality agreements and do not retain your data for model training.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-slate-800">6. Your Rights (GDPR & CCPA Compliance)</h2>
              <p className="mt-3">
                Depending on your location, you may have the following rights regarding your data:
              </p>
              <ul className="mt-3 list-disc pl-5 space-y-2">
                <li><strong>Right to Access:</strong> Request a copy of the personal data we hold about you.</li>
                <li><strong>Right to be Forgotten:</strong> Request the permanent deletion of your account and all associated uploaded documents from our servers.</li>
                <li><strong>Right to Rectification:</strong> Request correction of inaccurate data.</li>
              </ul>
              <p className="mt-3">
                To exercise these rights, please contact us at our designated support email.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-slate-800">7. Changes to This Policy</h2>
              <p className="mt-3">
                We may update this Privacy Policy from time to time to reflect changes in our practices or legal requirements. We will notify you of any material changes by posting the updated policy on this page and updating the "Effective Date."
              </p>
            </section>
          </div>
        </ScrollReveal>
      </div>
    </PageTransition>
  );
}
